import { writeFile } from "node:fs/promises";

const CSV_ROOT = "https://raw.githubusercontent.com/PokeAPI/pokeapi/master/data/v2/csv";
const LANGUAGE_ES = "7";
const LANGUAGE_EN = "9";

const SOURCES = {
  moves: ["moves.csv", "move_names.csv", "move_id"],
  abilities: ["abilities.csv", "ability_names.csv", "ability_id"],
  items: ["items.csv", "item_names.csv", "item_id"],
  natures: ["natures.csv", "nature_names.csv", "nature_id"],
};

function toId(text) {
  return String(text || "").toLowerCase().replace(/[^a-z0-9]+/g, "");
}

function parseCsv(text) {
  const rows = [];
  let row = [];
  let value = "";
  let quoted = false;

  for (let index = 0; index < text.length; index += 1) {
    const char = text[index];
    const next = text[index + 1];

    if (quoted) {
      if (char === '"' && next === '"') {
        value += '"';
        index += 1;
      } else if (char === '"') {
        quoted = false;
      } else {
        value += char;
      }
      continue;
    }

    if (char === '"') quoted = true;
    else if (char === ",") {
      row.push(value);
      value = "";
    } else if (char === "\n") {
      row.push(value.replace(/\r$/, ""));
      rows.push(row);
      row = [];
      value = "";
    } else {
      value += char;
    }
  }

  if (value || row.length) {
    row.push(value.replace(/\r$/, ""));
    rows.push(row);
  }

  const [header, ...body] = rows;
  return body
    .filter((line) => line.length === header.length)
    .map((line) => Object.fromEntries(header.map((key, index) => [key, line[index]])));
}

async function fetchCsv(file) {
  const res = await fetch(`${CSV_ROOT}/${file}`);
  if (!res.ok) throw new Error(`${res.status} ${res.statusText}: ${file}`);
  return parseCsv(await res.text());
}

async function buildCategory([entityFile, nameFile, nameIdField]) {
  const [entities, names] = await Promise.all([fetchCsv(entityFile), fetchCsv(nameFile)]);
  const identifiers = new Map(entities.map((entry) => [entry.id, entry.identifier]));
  const localized = new Map();

  for (const row of names) {
    if (row.local_language_id !== LANGUAGE_ES && row.local_language_id !== LANGUAGE_EN) continue;
    const id = row[nameIdField];
    if (!localized.has(id)) localized.set(id, {});
    localized.get(id)[row.local_language_id === LANGUAGE_ES ? "es" : "en"] = row.name;
  }

  const output = {};
  for (const [id, namesForId] of localized.entries()) {
    if (!namesForId.en || !namesForId.es) continue;
    const keys = new Set([toId(namesForId.en), toId(identifiers.get(id))]);
    for (const key of keys) {
      if (key && namesForId.es !== namesForId.en) output[key] = namesForId.es;
    }
  }
  return Object.fromEntries(Object.entries(output).sort(([a], [b]) => a.localeCompare(b)));
}

const es = {};
for (const [category, source] of Object.entries(SOURCES)) {
  console.log(`Building ${category} translations...`);
  es[category] = await buildCategory(source);
}

const output = `// Generated by scripts/build-locales.mjs from PokeAPI CSV localized names.\n` +
  `// Source: ${CSV_ROOT}\n` +
  `const POKEARK_LOCALES = ${JSON.stringify({ es }, null, 2)};\n`;

await writeFile("locales-data.js", output, "utf8");
console.log("Wrote locales-data.js");
